Fix operator config
stakater/slack-operator pull request #11
Opened 2020-10-05 09:50 UTC by rehanjaved237

2020-10-05 09:52 UTC, stakater-user commented
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/bc522e85e0767fc24d716f91bfa4efa100503d03/checks) has Failed!

2020-10-05 10:04 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-01537cca`

2020-10-05 10:35 UTC, ahmedwaleedmalik requested changes
Please move the methods `getConfigSecretName` and `readSlackTokenSecret` to `config/config.go` file. And remove any redundant methods from there

2020-10-05 10:35 UTC, ahmedwaleedmalik commented on go.mod
> +	github.com/prometheus/common v0.9.1
Please run `go mod tidy` once

2020-10-05 10:35 UTC, ahmedwaleedmalik commented on main.go
> +	"github.com/prometheus/common/log"
Don't use `log` from this module

2020-10-05 10:35 UTC, ahmedwaleedmalik commented on main.go
> +		log.Info("CONFIG_SECRET_NAME is unset, using default value: " + SlackDefaultSecretName)
Replace `log` with `setupLog`

2020-10-05 11:06 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-aa6c5b89`

2020-10-05 13:11 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-c8ca557c`

2020-10-05 13:25 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-1b8ac55d`

2020-10-05 17:00 UTC, rasheedamir commented on config/manager/kustomization.yaml
> +  newTag: SNAPSHOT-PR-11-c8ca557c
hard code tag name?

2020-10-06 11:00 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-17efd9d6`

2020-10-06 14:05 UTC, stakater-user commented
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-84ab8c35`

2020-10-06 14:12 UTC, ahmedwaleedmalik approved these changes
LGTM

2020-10-06 14:15 UTC, stakater-user commented
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-49a21a26`

2020-10-06 14:15 UTC, stakater-user commented
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-11-f0f5e770`

2020-10-06 14:17 UTC, merged