WIP: Add functionality for unarchiving channel
stakater/slack-operator pull request #32
Opened 2020-12-28 10:16 UTC by rehanjaved237

2020-12-28 10:18 UTC, stakater-user commented
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/8818fe39d15baeae79768fdcc66667a61c13d25e/checks) has Failed!

2020-12-29 07:39 UTC, stakater-user commented
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/slack-operator/commit/458aa6cfd8d48f2ad544163be6cf54ab83fcbb1f/checks) has Failed!

2020-12-29 10:45 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-32-4300c044`

2020-12-29 11:03 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-32-e3f8150f`

2020-12-29 11:07 UTC, ahmedwaleedmalik requested changes

2020-12-29 11:07 UTC, ahmedwaleedmalik commented on controllers/channel_controller.go
> +			if err.Error() == "name_taken" && os.Getenv("ENABLE_UNARCHIVING_CHANNEL") == "true" {
Create a method to check `os.Getenv("ENABLE_UNARCHIVING_CHANNEL") == "true"`

2020-12-29 14:55 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/slack-operator:SNAPSHOT-PR-32-551e1fff`

2020-12-30 10:29 UTC, ahmedwaleedmalik approved these changes
LGTM

2020-12-30 10:29 UTC, merged